"""Add new fields to coding question

Revision ID: 3d512104b8fe
Revises: 3790dfb29f73
Create Date: 2023-10-12 11:51:48.126717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d512104b8fe'
down_revision = '3790dfb29f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('option_A', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('option_B', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('option_C', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('option_D', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coding_question_pkey')
    )
    # ### end Alembic commands ###
